const SCRIPT_URL="https://script.google.com/macros/s/AKfycbzpO6euL2RpDOZ1ZNab3cGvkyO-P38juCWLGrvVCRfhT9iQ6qC688Hxp6OBwQd_G6PQsA/exec";
const state={eintraege:[],taetigkeiten:[],kalenderDatum:new Date(),originalDatum:null,ausgewaehlt:null,soll:6,gesamtSaldo:0};
const $=id=>document.getElementById(id),form=$("entryForm"),datum=$("datum"),taetigkeit=$("taetigkeit"),freieTaetigkeit=$("freieTaetigkeit"),freieBox=$("freieTaetigkeitBox"),stunden=$("stunden"),abwesenheit=$("abwesenheit"),notiz=$("notiz"),meldung=$("meldung");
const saveButton=$("saveButton"),updateButton=$("updateButton"),deleteButton=$("deleteButton"),cancelButton=$("cancelButton"),buttonRow=$("buttonRow");
window.addEventListener("load",init);form.addEventListener("submit",speichern);updateButton.onclick=aktualisieren;deleteButton.onclick=loeschen;cancelButton.onclick=()=>bearbeitungBeenden();
$("prevMonth").onclick=()=>monatWechseln(-1);$("nextMonth").onclick=()=>monatWechseln(1);datum.onchange=datumGeaendert;abwesenheit.onchange=handleAbwesenheit;taetigkeit.onchange=handleFreieTaetigkeit;

async function init(){datum.value=iso(new Date());state.ausgewaehlt=datum.value;state.kalenderDatum=ausIso(datum.value);handleAbwesenheit();await ladeMonat();}
async function ladeMonat(){try{zeige("Lade Daten ...","");const r=await jsonp({action:"init",jahr:state.kalenderDatum.getFullYear(),monat:state.kalenderDatum.getMonth()+1});if(!r.ok)throw new Error(r.message);state.eintraege=r.eintraege||[];state.taetigkeiten=r.taetigkeiten||[];state.soll=Number(r.sollstunden)||6;state.gesamtSaldo=Number(r.gesamtSaldo)||0;renderListe();renderKalender();renderWoche();renderStatistik();zeige("","");}catch(e){zeige("Fehler: "+e.message,"error");}}
function formularDaten(){const frei=taetigkeit.value==="Andere Tätigkeit …";return{datum:datum.value,taetigkeit:frei?freieTaetigkeit.value.trim():taetigkeit.value,freieTaetigkeit:frei,stunden:stunden.value,abwesenheit:abwesenheit.value,notiz:notiz.value};}
function validiere(d){if(!d.datum)return"Bitte Datum auswählen.";if(d.abwesenheit)return"";if(!d.taetigkeit)return"Bitte Tätigkeit auswählen oder eintragen.";const h=Number(d.stunden);if(!Number.isFinite(h)||h<=0||h>24)return"Bitte gültige Stunden zwischen 0,25 und 24 eintragen.";return"";}
async function speichern(e){e.preventDefault();const d=formularDaten(),f=validiere(d);if(f)return zeige(f,"error");if(state.eintraege.some(x=>x.datum===d.datum))return zeige("Für dieses Datum gibt es bereits einen Eintrag.","error");await aktion("save",d);}
async function aktualisieren(){if(!state.originalDatum)return;const d={...formularDaten(),originalDatum:state.originalDatum},f=validiere(d);if(f)return zeige(f,"error");await aktion("update",d);}
async function loeschen(){if(!state.originalDatum||!confirm("Eintrag wirklich löschen?"))return;await aktion("delete",{datum:state.originalDatum});}
async function aktion(action,payload){buttons(true);zeige("Bitte warten ...","");try{const r=await jsonp({action,payload:JSON.stringify(payload)});if(!r.ok)throw new Error(r.message);zeige(r.message||"Erledigt ✅","success");const z=ausIso(action==="delete"?state.originalDatum:payload.datum);state.kalenderDatum=new Date(z.getFullYear(),z.getMonth(),1);state.ausgewaehlt=iso(z);bearbeitungBeenden(false);datum.value=state.ausgewaehlt;await ladeMonat();}catch(e){zeige("Fehler: "+e.message,"error");}finally{buttons(false);}}
function eintragLaden(e){state.originalDatum=e.datum;state.ausgewaehlt=e.datum;datum.value=e.datum;const fest=state.taetigkeiten.includes(e.taetigkeit)&&e.taetigkeit!=="Andere Tätigkeit …";taetigkeit.value=fest?e.taetigkeit:"Andere Tätigkeit …";freieTaetigkeit.value=fest?"":e.taetigkeit;stunden.value=e.stunden||"";abwesenheit.value=e.abwesenheit||"";notiz.value=e.notiz||"";handleFreieTaetigkeit();handleAbwesenheit();editMode(true);window.scrollTo({top:0,behavior:"smooth"});}
function bearbeitungBeenden(heute=true){state.originalDatum=null;editMode(false);taetigkeit.value="";freieTaetigkeit.value="";stunden.value="";abwesenheit.value="";notiz.value="";if(heute){datum.value=iso(new Date());state.ausgewaehlt=datum.value;}handleFreieTaetigkeit();handleAbwesenheit();}
function editMode(a){saveButton.hidden=a;updateButton.hidden=!a;deleteButton.hidden=!a;buttonRow.classList.toggle("edit-mode",a);}
function buttons(a){[saveButton,updateButton,deleteButton,cancelButton].forEach(b=>b.disabled=a);}
function handleFreieTaetigkeit(){freieBox.classList.toggle("hidden",taetigkeit.value!=="Andere Tätigkeit …");}
function handleAbwesenheit(){const a=!!abwesenheit.value;taetigkeit.disabled=a;stunden.disabled=a;freieTaetigkeit.disabled=a;if(a){taetigkeit.value="";freieTaetigkeit.value="";stunden.value="";handleFreieTaetigkeit();}}
function renderListe(){const alt=taetigkeit.value;taetigkeit.innerHTML='<option value="">Bitte wählen</option>';state.taetigkeiten.forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=v;taetigkeit.appendChild(o)});if(state.taetigkeiten.includes(alt))taetigkeit.value=alt;handleFreieTaetigkeit();}
function renderKalender(){const y=state.kalenderDatum.getFullYear(),m=state.kalenderDatum.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),offset=(first.getDay()+6)%7,heute=iso(new Date()),map=new Map(state.eintraege.map(e=>[e.datum,e]));$("monthLabel").textContent=state.kalenderDatum.toLocaleString("de-DE",{month:"long",year:"numeric"});const g=$("calendarGrid");g.innerHTML="";["Mo","Di","Mi","Do","Fr","Sa","So"].forEach(n=>{const d=document.createElement("div");d.className="day-name";d.textContent=n;g.appendChild(d)});for(let i=0;i<offset;i++){const d=document.createElement("div");d.className="day-cell empty";g.appendChild(d)}for(let tag=1;tag<=last.getDate();tag++){const dt=new Date(y,m,tag),i=iso(dt),e=map.get(i),b=document.createElement("button");b.type="button";b.className="day-cell "+(e?(e.abwesenheit?"status-abwesenheit":"status-arbeit"):"status-offen")+(i===heute?" today":"")+(i===state.ausgewaehlt?" selected":"");b.innerHTML=`<span class="day-number">${tag}</span><span class="status-label">${e?(e.abwesenheit||kurz(e.taetigkeit)):""}</span>`;b.onclick=()=>{state.ausgewaehlt=i;datum.value=i;if(e)eintragLaden(e);else{bearbeitungBeenden(false);datum.value=i;state.ausgewaehlt=i;}renderKalender();renderWoche();};g.appendChild(b);}}
function renderWoche(){const d=ausIso(state.ausgewaehlt||datum.value),kw=isoWoche(d),jahr=isoJahr(d),ein=state.eintraege.filter(e=>{const x=ausIso(e.datum);return isoWoche(x)===kw&&isoJahr(x)===jahr}),ist=ein.reduce((s,e)=>s+Number(e.anrechenbar||0),0),saldo=ist-state.soll;$("weekBox").innerHTML=`<strong>Diese Woche: ${format(ist)} von ${format(state.soll)} Stunden</strong><span>Wochensaldo: ${vorzeichen(saldo)} Stunden</span>`;}
function renderStatistik(){const h=state.eintraege.reduce((s,e)=>s+Number(e.stunden||0),0);$("statStunden").textContent=format(h);setSaldo($("statGesamtSaldo"),state.gesamtSaldo);}
function setSaldo(el,v){el.textContent=vorzeichen(v);el.classList.toggle("plus",v>0);el.classList.toggle("minus",v<0);}
function vorzeichen(v){return(v>0?"+":"")+format(v)}
async function datumGeaendert(){if(!datum.value)return;state.ausgewaehlt=datum.value;const d=ausIso(datum.value),w=d.getFullYear()!==state.kalenderDatum.getFullYear()||d.getMonth()!==state.kalenderDatum.getMonth();state.kalenderDatum=new Date(d.getFullYear(),d.getMonth(),1);if(w)await ladeMonat();else{renderKalender();renderWoche();}}
async function monatWechseln(r){state.kalenderDatum=new Date(state.kalenderDatum.getFullYear(),state.kalenderDatum.getMonth()+r,1);state.ausgewaehlt=iso(state.kalenderDatum);datum.value=state.ausgewaehlt;await ladeMonat();}
function jsonp(p){return new Promise((res,rej)=>{if(SCRIPT_URL.includes("HIER_"))return rej(new Error("Bitte zuerst die Apps-Script-URL in app.js eintragen."));const cb="nebenjob"+Date.now()+Math.random().toString(36).slice(2),s=document.createElement("script"),t=setTimeout(()=>{clean();rej(new Error("Zeitüberschreitung beim Apps Script."))},15000);function clean(){clearTimeout(t);delete window[cb];s.remove()}window[cb]=d=>{clean();res(d)};s.src=SCRIPT_URL+"?"+new URLSearchParams({...p,callback:cb,zeit:Date.now()});s.onerror=()=>{clean();rej(new Error("Verbindung zum Apps Script fehlgeschlagen."))};document.head.appendChild(s)});}
function iso(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}function ausIso(s){const[a,b,c]=s.split("-").map(Number);return new Date(a,b-1,c)}
function isoWoche(d){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-y)/86400000)+1)/7)}function isoJahr(d){const x=new Date(d);x.setDate(x.getDate()+4-(x.getDay()||7));return x.getFullYear()}
function kurz(t){return String(t||"").length>8?String(t).slice(0,7)+"…":String(t||"")}function format(v){return Number(v||0).toLocaleString("de-DE",{maximumFractionDigits:2})}function zeige(t,k){meldung.textContent=t;meldung.className=k||""}
